# Generated by Django 4.2.19 on 2025-03-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zoo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zookeeper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("qualifications", models.TextField()),
                (
                    "assigned_animals",
                    models.ManyToManyField(
                        blank=True, related_name="zookeepers", to="zoo.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("feeding", "Feeding"),
                            ("medical", "Medical Checkup"),
                            ("cleaning", "Cleaning"),
                        ],
                        max_length=100,
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zoo.animal"
                    ),
                ),
                (
                    "zookeeper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zoo.zookeeper"
                    ),
                ),
            ],
        ),
    ]
