# Generated by Django 4.2.19 on 2025-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zoo", "0003_membershiptier_specialevent_membership_eventbooking"),
    ]

    operations = [
        migrations.RemoveField(model_name="membershiptier", name="benefits",),
        migrations.RemoveField(model_name="membershiptier", name="cost",),
        migrations.AddField(
            model_name="membershiptier",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="membershiptier",
            name="name",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Silver", "Silver"),
                    ("Gold", "Gold"),
                    ("Premium", "Premium"),
                    ("VIP", "VIP"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
